name: Job Hunter FINAL TEST

on:
  workflow_dispatch: # 手動実行用

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests selenium webdriver-manager

      - name: Run script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: |
          # ここで「アンダーバー」の方だけを指名して実行！
          python job_hunt_app.py
